name: 'Machine Translator'
description: 'Automatically create machine-translated PRs of translation files. Supports: .resx, .restext, .ini, .xliff, .po, and .json.'
branding:
  icon: flag
  color: blue
inputs:
  sourceLocale:
    description: 'The source locale (for example, ''en'') used to create the glob pattern for finding translation (**/*.en.resx) files as input.'
    required: true
  subscriptionKey:
    description: 'The Azure Cognitive Services translator resource subscription key.'
    required: true
  endpoint:
    description: 'The Azure Cognitive Services translator resource endpoint.'
    required: true
  region:
    description: 'The Azure Cognitive Services translator resource region. This is optional when using a global translator resource.'
    required: false
  toLocales:
    description: 'Optional locales to translate to, otherwise all possible locales are targeted. Example input, ''"es,de,fr"'' or ''["es","de","fr"]''. Requires double quotes.'
    required: false
outputs:
  summary-title:
    description: 'The summary details as a title, for example: "Machine-translated 320 files, a total of 5,418 translations"'
  summary-message:
    description: 'GitHub flavored markdown translation summary, with details of the resulting translations.'
  has-new-translations:
    description: 'A boolean value, indicating whether or not new translations exist as a result of running this action.'
runs:
  using: 'node16'
  main: 'dist/resource-translator/index.js'
